title: Place Matters: Regional Risks in Breast Cancer Mortality
description: Data Science Portfolio
remote_theme: yaoyao-liu/minimal-light
plugins:
  - jekyll-remote-theme
url: "https://Blackfemalebreastcancernis.github.io"
baseurl: ""
